namespace :db do
  desc 'database console'
  task :console do
    sh 'sequel -e development config/database.yml'
  end

  desc 'drop database'
  task :drop do
    sh 'rm db/development.sqlite3'
  end

  desc 'migrate database'
  task :migrate do
    sh 'sequel -e development -m db/migrations config/database.yml'
  end

  desc 'seed database'
  task :seed do
    require './db/seed'
  end
end

desc 'pry console'
task :console do
  require 'pry'
  require './buckets'
  Buckets.connect
  binding.pry
end
