name:     Buckets
version:  v1
formats:
  in:   [json, xml]
  out:  [json, xml]
api:
- resource: buckets
  contains:
  - desc: List buckets
    get:
    code: Bucket.all
  - desc: Create a bucket
    post:
    code: Bucket.create
  - resource: :bucket_id
    contains:
    - desc: Read a bucket
      get:
      code: |
        Bucket[params[:bucket_id]]
    - desc: Update a bucket
      put:
      code: |
        Bucket[params[:bucket_id]].set(...)
    - desc: Delete a bucket
      delete:
      code: |
        Bucket.where(id: params[bucket_id]).delete
    - resource: objects
      contains:
      - get:
        code:
      - post:
        code:
      - resource: :object_id
        contains:
        - get:
          code:
        - put:
          code:
        - delete:
          code:
- resource: users
  contains:
  - get:
    code:
  - post:
    code:
  - resource: :user_id
    contains:
    - get:
      code:
    - put:
      code:
    - delete:
      code:
