name:     Buckets
version:  v1
api:
- resource: buckets
  formats:
    in:   [json, xml]
    out:  [json, xml]
  contains:
  - desc: List buckets
    get: Bucket.all
  - desc: Create a bucket
    post: Bucket.create
  - resource: :bucket_id
    contains:
    - desc: Read a bucket
      get: |
        Bucket[params[:bucket_id]]
    - desc: Update a bucket
      put: |
        Bucket[params[:bucket_id]].set(...)
    - desc: Delete a bucket
      delete: |
        Bucket.where(id: params[bucket_id]).delete
    - resource: objects
      contains:
      - get:
      - post:
      - resource: :object_id
        contains:
        - get:
        - put:
        - delete:
- resource: users
  contains:
  - get:
  - post:
  - resource: :user_id
    contains:
    - get:
    - put:
    - delete:
