models:
  bucket:
    one_to_many:  objects
    one_to_one:   user
  object:
    one_to_one:   bucket
    one_through_one:
      name:       user
      join_table: buckets
  user:
    one_to_many:  buckets
    many_through_many:
      name:       objects
      join_table: buckets

migrations:
  - create_table: buckets
    fields:
    - primary_key: id
    - foreign_key: [user_id, users]
  - create_table: objects
    fields:
    - primary_key: id
    - foreign_key: [bucket_id, buckets]
  - create_table: users
    fields:
    - primary_key: id
    - String:
        name:   name
        unique: true
        null:   false
  - create_table: shares
    fields:
    - primary_key: [user_id, bucket_id]
