name:     Chat
version:  v1
request_choices:  [json, xml]
response_choices: [json, xml]
api:
- resource: rooms
  contains:
  - desc: Get current rooms
    get:  get_current_rooms
  - resource: :room
    contains:
    - resource: join
      contains:
      - desc: Join a room
        post: join_room
    - resource: messages
      contains:
      - desc: Stream messages in room
        get:  stream_messages_in_room
    - resource: post
      contains:
      - desc: Post to room
        post: post_to_room
